package com.panihari.orders;
import android.Manifest; import android.app.*; import android.bluetooth.*; import android.content.*; import android.content.pm.PackageManager; import android.hardware.usb.*; import android.os.*; import android.util.Base64; import android.webkit.*; import java.io.OutputStream; import java.util.*; import java.util.concurrent.*;
public class MainActivity extends Activity {
 static final int REQ_BT=4101; static final String USB_PERMISSION="com.panihari.orders.USB_PERMISSION"; WebView webView; final PrinterBridge bridge=new PrinterBridge();
 public void onCreate(Bundle b){super.onCreate(b);webView=new WebView(this);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);s.setLoadWithOverviewMode(true);s.setUseWideViewPort(true);webView.setWebViewClient(new WebViewClient());webView.setWebChromeClient(new WebChromeClient());webView.addJavascriptInterface(bridge,"VasukiPrinter");webView.loadUrl("file:///android_asset/owner.html");requestBt();}
 void requestBt(){if(Build.VERSION.SDK_INT>=31){ArrayList<String> m=new ArrayList<>();if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)m.add(Manifest.permission.BLUETOOTH_CONNECT);if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)m.add(Manifest.permission.BLUETOOTH_SCAN);if(!m.isEmpty())requestPermissions(m.toArray(new String[0]),REQ_BT);}}
 @Override public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
 public class PrinterBridge { BluetoothSocket sock; OutputStream out; UsbDeviceConnection uc; UsbEndpoint uo; String name="";
  @JavascriptInterface public String connectPrinter(){final String[] c=new String[1];CountDownLatch l=new CountDownLatch(1);runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Connect Thermal Printer").setItems(new String[]{"Bluetooth Classic","USB OTG"},(d,w)->{c[0]=w==0?"bt":"usb";l.countDown();}).setOnCancelListener(d->l.countDown()).show());try{l.await(60,TimeUnit.SECONDS);}catch(Exception e){}if(c[0]==null)return "Cancelled";return "bt".equals(c[0])?connectBt():connectUsb();}
  String connectBt(){try{if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){runOnUiThread(()->requestBt());return "Allow Bluetooth permission and tap again";}BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null)return "Bluetooth not supported";if(!a.isEnabled())return "Turn Bluetooth ON first";Set<BluetoothDevice> set=a.getBondedDevices();if(set==null||set.isEmpty())return "Pair printer in tablet Bluetooth settings first";ArrayList<BluetoothDevice> ds=new ArrayList<>(set);String[] ns=new String[ds.size()];for(int i=0;i<ds.size();i++){String n=ds.get(i).getName();ns[i]=(n==null?"Bluetooth device":n)+"\n"+ds.get(i).getAddress();}final int[] sel={-1};CountDownLatch l=new CountDownLatch(1);runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Select paired printer").setItems(ns,(d,w)->{sel[0]=w;l.countDown();}).setOnCancelListener(d->l.countDown()).show());l.await(60,TimeUnit.SECONDS);if(sel[0]<0)return "Cancelled";close();BluetoothDevice d=ds.get(sel[0]);UUID id=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");a.cancelDiscovery();try{sock=d.createRfcommSocketToServiceRecord(id);sock.connect();}catch(Exception x){try{sock.close();}catch(Exception z){}sock=d.createInsecureRfcommSocketToServiceRecord(id);sock.connect();}out=sock.getOutputStream();name=d.getName()==null?"Bluetooth Printer":d.getName();return name;}catch(Exception e){close();return "Bluetooth error: "+msg(e);}}
  String connectUsb(){try{UsbManager m=(UsbManager)getSystemService(USB_SERVICE);ArrayList<UsbDevice> ds=new ArrayList<>(m.getDeviceList().values());if(ds.isEmpty())return "Connect USB printer with OTG cable first";String[] ns=new String[ds.size()];for(int i=0;i<ds.size();i++){UsbDevice d=ds.get(i);ns[i]=(d.getProductName()==null?"USB Printer":d.getProductName())+" ("+d.getVendorId()+":"+d.getProductId()+")";}final int[] sel={-1};CountDownLatch l=new CountDownLatch(1);runOnUiThread(()->new AlertDialog.Builder(MainActivity.this).setTitle("Select USB printer").setItems(ns,(d,w)->{sel[0]=w;l.countDown();}).setOnCancelListener(d->l.countDown()).show());l.await(60,TimeUnit.SECONDS);if(sel[0]<0)return "Cancelled";UsbDevice d=ds.get(sel[0]);if(!m.hasPermission(d)){CountDownLatch pl=new CountDownLatch(1);final boolean[] ok={false};BroadcastReceiver r=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(USB_PERMISSION.equals(i.getAction())){ok[0]=i.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED,false);pl.countDown();}}};IntentFilter f=new IntentFilter(USB_PERMISSION);if(Build.VERSION.SDK_INT>=33)registerReceiver(r,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(r,f);int fl=PendingIntent.FLAG_UPDATE_CURRENT;if(Build.VERSION.SDK_INT>=31)fl|=PendingIntent.FLAG_MUTABLE;m.requestPermission(d,PendingIntent.getBroadcast(MainActivity.this,0,new Intent(USB_PERMISSION),fl));pl.await(60,TimeUnit.SECONDS);try{unregisterReceiver(r);}catch(Exception x){}if(!ok[0])return "USB permission denied";}UsbInterface ui=null;UsbEndpoint ep=null;for(int i=0;i<d.getInterfaceCount()&&ep==null;i++){UsbInterface q=d.getInterface(i);for(int e=0;e<q.getEndpointCount();e++){UsbEndpoint p=q.getEndpoint(e);if(p.getDirection()==UsbConstants.USB_DIR_OUT&&p.getType()==UsbConstants.USB_ENDPOINT_XFER_BULK){ui=q;ep=p;break;}}}if(ui==null||ep==null)return "USB printer has no bulk OUT endpoint";close();uc=m.openDevice(d);if(uc==null)return "Unable to open USB printer";if(!uc.claimInterface(ui,true))return "Unable to claim USB printer";uo=ep;name=d.getProductName()==null?"USB Printer":d.getProductName();return name;}catch(Exception e){close();return "USB error: "+msg(e);}}
  @JavascriptInterface public String printBase64(String b){try{byte[] data=Base64.decode(b,Base64.DEFAULT);if(out!=null){out.write(data);out.flush();return "OK";}if(uc!=null&&uo!=null){for(int o=0;o<data.length;){int n=Math.min(4096,data.length-o);byte[] ch=Arrays.copyOfRange(data,o,o+n);if(uc.bulkTransfer(uo,ch,n,5000)<0)throw new Exception("USB transfer failed");o+=n;}return "OK";}return "Printer not connected";}catch(Exception e){return "Print error: "+msg(e);}}
  @JavascriptInterface public String printText(String t){return printBase64(Base64.encodeToString(t.getBytes(),Base64.NO_WRAP));}@JavascriptInterface public String disconnectPrinter(){close();name="";return "Disconnected";}@JavascriptInterface public String getConnectedPrinter(){return name;}
  void close(){try{if(out!=null)out.close();}catch(Exception e){}try{if(sock!=null)sock.close();}catch(Exception e){}try{if(uc!=null)uc.close();}catch(Exception e){}out=null;sock=null;uc=null;uo=null;}String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
 }
}
